# Generated by Django 3.0.3 on 2020-02-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='p1',
            field=models.ImageField(blank=True, null=True, upload_to='jigsaw/static/pics'),
        ),
        migrations.AddField(
            model_name='picture',
            name='p2',
            field=models.ImageField(blank=True, null=True, upload_to='jigsaw/static/pics'),
        ),
        migrations.AddField(
            model_name='picture',
            name='p3',
            field=models.ImageField(blank=True, null=True, upload_to='jigsaw/static/pics'),
        ),
        migrations.AddField(
            model_name='picture',
            name='p4',
            field=models.ImageField(blank=True, null=True, upload_to='jigsaw/static/pics'),
        ),
        migrations.AddField(
            model_name='picture',
            name='wr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='jigsaw/static/pics'),
        ),
    ]
