# Generated by Django 3.0.3 on 2020-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0002_auto_20200216_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='wr',
        ),
        migrations.AlterField(
            model_name='picture',
            name='p1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p3',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p4',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
