# Generated by Django 3.0.3 on 2020-02-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0003_auto_20200216_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='p4',
        ),
        migrations.AddField(
            model_name='picture',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
